### ISSUE TITLE
Not working for quarantined subreddits

### ISSUE THREAD

**Issue by J0s3f** [Jameak/ImageDownloader#3]
[Quarantined ](https://www.reddithelp.com/en/categories/reddit-101/rules-reporting/account-and-community-restrictions/quarantined-subreddits)reddits cannot be viewed unless logged in with an account with verified email.
Because of this, posts from such reddits cannot be downloaded currently with ImageDownloader

**Comment by Jameak** [comment]
This is, as you said, unfortunately a limitation with how ImageDownloader accesses the Reddit API currently.

A solution would be to add optional reddit user authentication so that the user could use their own account to opt-in to seeing the subreddit on the reddit website and then access the content through the API afterward as per [this reddit post](https://www.reddit.com/r/redditdev/comments/3fx3gt) since quarantined subreddits dont seem to have their own authenticated endpoint.
