### ISSUE TITLE
Suggestion: Adding a Multithreading/Processing option

### ISSUE THREAD

**Issue by kk-Chiron** [Jameak/ImageDownloader#7]
Love this downloader. A option to determine multiple threads to make the downloading process much faster would be really nice to have. Could you add something like this?

**Comment by Jameak** [comment]
The program is already multithreaded for the important parts of the workload.

The downloading process has two steps:
* First we retrieve a list of all image-urls that need to be downloaded. This is not parallelized.
* Afterward, we download the images. This download is parallelized, but limited to 8 threads to not hammer the image-hosts (which could make them temporarily IP-ban the user) and to not oversaturate the internet connection. 8 threads was chosen arbitrarily and could probably be increased if you're finding it much too slow.

The initial retrieval of image-urls is not parallelized because there is little need for it. Depending on the host (Imgur or Reddit) that we pull data for, we do the following:
* Imgur album: Retrieving the required data only takes a single API call.
* Imgur account: Retrieving all the images that a specific user uploaded makes one API call per 50 images. (This will abort when Imgur starts rate-limiting us, so a max of 500 requests can be executed here)
* Reddit: When pulling data from reddit, we can pull info from up to 1000 posts. The default number of posts that we grab per request is 25, for a total of 40 requests for post information. If every post is a supported Imgur- or Deviantart-link then we do one more API call for a total worst-case of 1040 web-requests.
    * In the context of the time it would take to download the images from all 1040 links (some of which may be albums with an arbitrary number of images), the time taken during these initial requests is negligible and not worth parallelizing.
